language: node.js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli bower
install:
  - npm install
  - cd testrunner
  - bower install
  - cd ..
before_script:
  - grunt build
script:
  - grunt test --sim=3.0
